title: Github experience
author: XLJasonHuo  
email: jhuo1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new site, in here we're going to talk about my experience on Github. I've only just started using
  Github today, but everything has been great so far.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
